version: '3'
services:
  training_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    volumes:
      - './:/app:cached'
      - '/app/node_modules'
    depends_on:
      - training_db
    environment:
      - CHOKIDAR_USEPOLLING=true

  training_db:
    image: postgres
    volumes:
      - ./training_track.sql:/docker-entrypoint-initdb.d/training_track.sql
      - training_db:/data/training_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vila@02100260
      POSTGRES_DB: training_track
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  training_db:
