FROM node:16-bullseye-slim

WORKDIR /app

COPY . .

#RUN chown -R node:node /root/.npm
ENV npm_config_cache /home/node/app/.npm

RUN npm install

RUN npx prisma generate
RUN npm run build



EXPOSE 3005

# Start the application
CMD ["npm", "start"]

